### ISSUE TITLE
Mercurial support

### ISSUE THREAD

**Issue by therealprologic** [coagulant/coveralls-python#30]
````python
$ coveralls 
Submitting coverage to coveralls.io...
Traceback (most recent call last):
  File "/Users/s2092651/bin/coveralls", line 9, in <module>
    load_entry_point('coveralls==0.2', 'console_scripts', 'coveralls')()
  File "/Users/s2092651/lib/python2.7/site-packages/coveralls/cli.py", line 48, in main
    result = coverallz.wear()
  File "/Users/s2092651/lib/python2.7/site-packages/coveralls/api.py", line 72, in wear
    data = self.create_data()
  File "/Users/s2092651/lib/python2.7/site-packages/coveralls/api.py", line 112, in create_data
    self._data.update(self.git_info())
  File "/Users/s2092651/lib/python2.7/site-packages/coveralls/api.py", line 146, in git_info
    'id': gitlog('%H'),
  File "/Users/s2092651/lib/python2.7/site-packages/coveralls/api.py", line 162, in gitlog
    return str(git('--no-pager', 'log', "-1", pretty="format:%s" % format))
  File "/Users/s2092651/lib/python2.7/site-packages/sh.py", line 726, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/Users/s2092651/lib/python2.7/site-packages/sh.py", line 291, in __init__
    self.wait()
  File "/Users/s2092651/lib/python2.7/site-packages/sh.py", line 295, in wait
    self._handle_exit_code(self.process.wait())
  File "/Users/s2092651/lib/python2.7/site-packages/sh.py", line 309, in _handle_exit_code
    self.process.stderr
sh.ErrorReturnCode_128: 

  RAN: '/usr/local/bin/git --no-pager log -1 --pretty=format:%H'

  STDOUT:


  STDERR:
fatal: Not a git repository (or any of the parent directories): .git
```

**Comment by coagulant** [comment]
Closing this, as this can't be done at this moment (no suupoer for bitbucket on coveralls.io part).
Feel free to reopen whenand if such support appears.

Current workaround is to maintain a mercurial mirror on github.
