### ISSUE TITLE
coveralls crashes when dealing with malformed encoding declaration

### ISSUE THREAD

**Issue by chmduquesne** [coagulant/coveralls-python#52]
My project has source code that contains utf-8 (some of my tests are checking if my code works with weird inputs). My tests run fine and the python coverage tool also works fine, but coveralls crashes when processing it: see https://travis-ci.org/chmduquesne/ok/builds/43104434.

I am attaching the traceback:

    $ coveralls
    Submitting coverage to coveralls.io...
    Traceback (most recent call last):
    File "/usr/local/bin/coveralls", line 9, in <module>
    load_entry_point('coveralls==0.4.4', 'console_scripts', 'coveralls')()
    File "/usr/local/lib/python2.7/dist-packages/coveralls/cli.py", line 49, in main
    result = coverallz.wear()
    File "/usr/local/lib/python2.7/dist-packages/coveralls/api.py", line 73, in wear
    data = self.create_data()
    File "/usr/local/lib/python2.7/dist-packages/coveralls/api.py", line 122, in create_data
    self._data = {'source_files': self.get_coverage()}
    File "/usr/local/lib/python2.7/dist-packages/coveralls/api.py", line 132, in get_coverage
    return reporter.report()
    File "/usr/local/lib/python2.7/dist-packages/coveralls/reporter.py", line 27, in report
    self.parse_file(cu, self.coverage._analyze(cu))
    File "/usr/local/lib/python2.7/dist-packages/coveralls/reporter.py", line 64, in parse_file
    source = source.decode(encoding).encode('utf-8')
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 1: ordinal not in range(128)

**Comment by coagulant** [comment]
I see you've fixed a problem with malformed encoding declaration: https://github.com/chmduquesne/ok/commit/bdbf3f60f3c7565812c3433b3db91ad624d84e8d

Thanks for reporting this problem

**Comment by chmduquesne** [comment]
Yes. My keyboard sometimes puts this weird white character instead of a
space, which apparently is not cool when you are declaring the encoding.
Python does not complain, but it makes coverage unhappy, as well as
coveralls. Sorry, I forgot to tell you that I fixed my code.
