### ISSUE TITLE
Coveralls merge fails when using python3

### ISSUE THREAD

**Issue by jessamynsmith** [coagulant/coveralls-python#56]
In a python3 environment, I get the following error when I try to use the --merge option:

```$ coveralls --merge=coverage.json --output=op.txt
Traceback (most recent call last):
  File "/Users/jessamyn/.virtualenvs/eggtimer/bin/coveralls", line 9, in <module>
    load_entry_point('coveralls==1.0a0', 'console_scripts', 'coveralls')()
  File "/Users/jessamyn/.virtualenvs/eggtimer/lib/python3.4/site-packages/coveralls-1.0a0-py3.4.egg/coveralls/cli.py", line 50, in main
  File "/Users/jessamyn/.virtualenvs/eggtimer/lib/python3.4/site-packages/coveralls-1.0a0-py3.4.egg/coveralls/api.py", line 74, in merge
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))```

**Comment by jessamynsmith** [comment]
This has been fixed with the merge of #57
