### ISSUE TITLE
Issue on Python 3: TypeError: the JSON object must be str, not 'bytes'

### ISSUE THREAD

**Issue by ionelmc** [coagulant/coveralls-python#88]
I get this [here](https://travis-ci.org/ionelmc/python-lazy-object-proxy/jobs/80676336#L1404)
```
  /home/travis/build/ionelmc/python-lazy-object-proxy$ /home/travis/build/ionelmc/python-lazy-object-proxy/.tox/coveralls/bin/coveralls --merge=extension-coveralls.json 

Traceback (most recent call last):

  File ".tox/coveralls/bin/coveralls", line 11, in <module>

    sys.exit(main())

  File "/home/travis/build/ionelmc/python-lazy-object-proxy/.tox/coveralls/lib/python3.4/site-packages/coveralls/cli.py", line 50, in main

    coverallz.merge(options['--merge'])

  File "/home/travis/build/ionelmc/python-lazy-object-proxy/.tox/coveralls/lib/python3.4/site-packages/coveralls/api.py", line 72, in merge

    extra = json.load(fh)

  File "/opt/python/3.4.2/lib/python3.4/json/__init__.py", line 268, in load

    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)

  File "/opt/python/3.4.2/lib/python3.4/json/__init__.py", line 312, in loads

    s.__class__.__name__))

TypeError: the JSON object must be str, not 'bytes'
```

**Comment by ionelmc** [comment]
Ignore me, this is not an issue on 1.0b1
